topic_scores:
  AI: 5
  ChatGPT: 5
  便利ツール: 5
  パソコン: 5
  スマホ: 4
  ガジェット: 4
  動画: 4
  ドラマ: 3
  YouTube: 4
  食べ物: 4
  健康: 4
  カフェ: 4
  ご飯: 4
  映画: 4
  料理: 3
  休日: 4
  休日の過ごし方: 4
  買い物: 3
  旅行: 2
  自然: 2
  遠出: 2
  アウトドア: 1
  フェス: 1
  スポーツ観戦: 1
  美容: 2
  ファッション: 2
  お酒: 2
  飲み: 2
  仕事終わり: 2
  投資: 3
  株: 3
  政治: 2
  都市伝説: 2

