export const DATA_SOURCES = {
  MOCK: { label: "モックデータ", tradable: false },
  J_QUANTS: { label: "J-Quants", tradable: true },
  TDNET: { label: "TDnet", tradable: true },
  CSV: { label: "CSV取込", tradable: false },
  MANUAL: { label: "手動入力", tradable: false }
};

const mockMeta = {
  market: "東証プライム MOCK",
  dataSource: "MOCK",
  dataSourceLabel: "モックデータ",
  lastUpdated: "サンプルデータ",
  isMock: true,
  isTradableData: false
};

export const mockStocks = {
  "7203": createMockStock({
    code: "7203",
    name: "トヨタ自動車 MOCK",
    aliases: ["トヨタ", "toyota"],
    price: 3298,
    previousClose: 3260,
    volume: 34800000,
    averageVolume20d: 24600000,
    ma25: 3150,
    ma75: 3010,
    rsi: 68,
    high52w: 3500,
    highYtd: 3500,
    latestEarningsDate: "2026-05-08",
    nextEarningsDate: "2026-08-06",
    earningsTrend: "GROWING",
    hasUpwardRevision: true,
    hasDownwardRevision: false,
    hasDividendIncrease: true,
    hasBuyback: true,
    importantDisclosures: ["上方修正サンプル", "増配サンプル", "自社株買いサンプル"],
    policyThemes: ["GX", "DX", "経済安全保障"],
    policyRelationType: "DIRECT",
    policyDescription: "電動化、電池、車載ソフトウェアが政策テーマと直接関係する想定サンプル。",
    candlePattern: "NORMAL",
    isBeforeEarnings: false,
    recentHighBreakout: false,
    postEarningsGood: false,
    exhaustionConcern: false,
    mockPattern: "上方修正・増配・自社株買いがあり、買いスコアが高い銘柄"
  }),
  "6758": createMockStock({
    code: "6758",
    name: "ソニーグループ MOCK",
    aliases: ["ソニー", "sony"],
    price: 15420,
    previousClose: 15630,
    volume: 6100000,
    averageVolume20d: 4300000,
    ma25: 14200,
    ma75: 13540,
    rsi: 78,
    high52w: 15820,
    highYtd: 15820,
    latestEarningsDate: "2026-05-14",
    nextEarningsDate: "2026-08-07",
    earningsTrend: "STABLE",
    hasUpwardRevision: false,
    hasDownwardRevision: false,
    hasDividendIncrease: false,
    hasBuyback: false,
    importantDisclosures: ["決算材料織り込みサンプル"],
    policyThemes: ["AI", "半導体", "データセンター"],
    policyRelationType: "INDIRECT",
    policyDescription: "画像センサーとコンテンツ制作基盤がAI需要の周辺テーマに関係する想定サンプル。",
    candlePattern: "VOLUME_SPIKE_UPPER_WICK",
    isBeforeEarnings: false,
    recentHighBreakout: true,
    postEarningsGood: false,
    exhaustionConcern: true,
    mockPattern: "RSIが高く、25日線乖離も大きく、高値掴み注意になる銘柄"
  }),
  "8035": createMockStock({
    code: "8035",
    name: "東京エレクトロン MOCK",
    aliases: ["東京エレクトロン", "東エレク", "tel"],
    price: 40100,
    previousClose: 39220,
    volume: 5200000,
    averageVolume20d: 2500000,
    ma25: 35600,
    ma75: 32200,
    rsi: 81,
    high52w: 40700,
    highYtd: 40700,
    latestEarningsDate: "2026-05-10",
    nextEarningsDate: "2026-08-12",
    earningsTrend: "GROWING",
    hasUpwardRevision: true,
    hasDownwardRevision: false,
    hasDividendIncrease: true,
    hasBuyback: false,
    importantDisclosures: ["上方修正サンプル", "増配サンプル"],
    policyThemes: ["半導体", "AI", "データセンター", "経済安全保障"],
    policyRelationType: "DIRECT",
    policyDescription: "半導体供給網とAI投資の中心テーマに直接関係する想定サンプル。",
    candlePattern: "NORMAL",
    isBeforeEarnings: false,
    recentHighBreakout: true,
    postEarningsGood: true,
    exhaustionConcern: false,
    mockPattern: "52週高値に近く、材料は強いが分割買い推奨になる銘柄"
  }),
  "9984": createMockStock({
    code: "9984",
    name: "ソフトバンクグループ MOCK",
    aliases: ["ソフトバンクグループ", "sbg"],
    price: 8120,
    previousClose: 8400,
    volume: 14800000,
    averageVolume20d: 9000000,
    ma25: 8650,
    ma75: 9100,
    rsi: 38,
    high52w: 11200,
    highYtd: 10550,
    latestEarningsDate: "2026-05-12",
    nextEarningsDate: "2026-08-09",
    earningsTrend: "DECLINING",
    hasUpwardRevision: false,
    hasDownwardRevision: true,
    hasDividendIncrease: false,
    hasBuyback: false,
    importantDisclosures: ["下方修正サンプル", "減益決算サンプル"],
    policyThemes: ["AI", "データセンター", "サイバーセキュリティ"],
    policyRelationType: "INDIRECT",
    policyDescription: "AI投資と通信インフラを通じて政策テーマに間接的に関係する想定サンプル。",
    candlePattern: "NORMAL",
    isBeforeEarnings: false,
    recentHighBreakout: false,
    postEarningsGood: false,
    exhaustionConcern: false,
    mockPattern: "下方修正・減益・25日線割れで見送りになる銘柄"
  }),
  "TEST01": createMockStock({
    code: "TEST01",
    name: "上方修正テスト銘柄 MOCK",
    aliases: ["上方修正テスト", "buy test"],
    price: 1850,
    previousClose: 1790,
    volume: 1600000,
    averageVolume20d: 900000,
    ma25: 1700,
    ma75: 1580,
    rsi: 64,
    high52w: 2200,
    highYtd: 2050,
    latestEarningsDate: "2026-05-15",
    nextEarningsDate: "2026-08-08",
    earningsTrend: "GROWING",
    hasUpwardRevision: true,
    hasDownwardRevision: false,
    hasDividendIncrease: true,
    hasBuyback: true,
    importantDisclosures: ["上方修正サンプル", "増配サンプル", "自社株買いサンプル"],
    policyThemes: ["DX"],
    policyRelationType: "INDIRECT",
    policyDescription: "業務DX需要を受ける想定サンプル。",
    candlePattern: "NORMAL",
    isBeforeEarnings: false,
    recentHighBreakout: true,
    postEarningsGood: true,
    exhaustionConcern: false,
    mockPattern: "上方修正・増配・自社株買いがあり、買いスコアが高い銘柄"
  }),
  "TEST02": createMockStock({
    code: "TEST02",
    name: "高値掴み注意テスト銘柄 MOCK",
    aliases: ["高値掴みテスト", "overheat test"],
    price: 4980,
    previousClose: 4920,
    volume: 2600000,
    averageVolume20d: 1200000,
    ma25: 4320,
    ma75: 3900,
    rsi: 84,
    high52w: 5050,
    highYtd: 5050,
    latestEarningsDate: "2026-05-01",
    nextEarningsDate: "2026-08-01",
    earningsTrend: "GROWING",
    hasUpwardRevision: true,
    hasDownwardRevision: false,
    hasDividendIncrease: true,
    hasBuyback: true,
    importantDisclosures: ["急騰サンプル", "上方修正サンプル", "増配サンプル", "自社株買いサンプル"],
    policyThemes: ["AI"],
    policyRelationType: "DIRECT",
    policyDescription: "AIテーマで急騰した想定サンプル。",
    candlePattern: "NORMAL",
    isBeforeEarnings: false,
    recentHighBreakout: true,
    postEarningsGood: true,
    exhaustionConcern: false,
    mockPattern: "RSIが高く、25日線乖離も大きく、高値掴み注意になる銘柄"
  }),
  "TEST03": createMockStock({
    code: "TEST03",
    name: "決算直前テスト銘柄 MOCK",
    aliases: ["決算直前テスト", "earnings test"],
    price: 1210,
    previousClose: 1205,
    volume: 510000,
    averageVolume20d: 500000,
    ma25: 1190,
    ma75: 1180,
    rsi: 54,
    high52w: 1500,
    highYtd: 1400,
    latestEarningsDate: "2026-02-05",
    nextEarningsDate: "2026-05-29",
    earningsTrend: "STABLE",
    hasUpwardRevision: false,
    hasDownwardRevision: false,
    hasDividendIncrease: false,
    hasBuyback: false,
    importantDisclosures: ["決算発表直前サンプル"],
    policyThemes: [],
    policyRelationType: "NONE",
    policyDescription: "主要な国策テーマとの関係は薄い想定サンプル。",
    candlePattern: "NORMAL",
    isBeforeEarnings: true,
    recentHighBreakout: false,
    postEarningsGood: false,
    exhaustionConcern: false,
    mockPattern: "決算直前で様子見になる銘柄"
  }),
  "TEST04": createMockStock({
    code: "TEST04",
    name: "国策未反応テスト銘柄 MOCK",
    aliases: ["国策未反応テスト", "policy test"],
    price: 860,
    previousClose: 852,
    volume: 420000,
    averageVolume20d: 390000,
    ma25: 850,
    ma75: 845,
    rsi: 49,
    high52w: 1240,
    highYtd: 1100,
    latestEarningsDate: "2026-05-11",
    nextEarningsDate: "2026-08-05",
    earningsTrend: "STABLE",
    hasUpwardRevision: false,
    hasDownwardRevision: false,
    hasDividendIncrease: false,
    hasBuyback: false,
    importantDisclosures: ["国策テーマ関連サンプル"],
    policyThemes: ["防衛", "宇宙", "経済安全保障"],
    policyRelationType: "DIRECT",
    policyDescription: "国策テーマに関係するが、株価はまだ大きく反応していない想定サンプル。",
    candlePattern: "NORMAL",
    isBeforeEarnings: false,
    recentHighBreakout: false,
    postEarningsGood: false,
    exhaustionConcern: false,
    mockPattern: "国策テーマ関連だが、まだ株価が大きく反応していない銘柄"
  }),
  "TEST05": createMockStock({
    code: "TEST05",
    name: "押し目待ちテスト銘柄 MOCK",
    aliases: ["押し目待ちテスト", "pullback test"],
    price: 2380,
    previousClose: 2410,
    volume: 820000,
    averageVolume20d: 700000,
    ma25: 2290,
    ma75: 2100,
    rsi: 58,
    high52w: 2800,
    highYtd: 2680,
    latestEarningsDate: "2026-05-13",
    nextEarningsDate: "2026-08-03",
    earningsTrend: "GROWING",
    hasUpwardRevision: false,
    hasDownwardRevision: false,
    hasDividendIncrease: true,
    hasBuyback: false,
    importantDisclosures: ["増配サンプル"],
    policyThemes: ["インバウンド"],
    policyRelationType: "INDIRECT",
    policyDescription: "訪日需要の回復テーマに間接的に関係する想定サンプル。",
    candlePattern: "NORMAL",
    isBeforeEarnings: false,
    recentHighBreakout: false,
    postEarningsGood: false,
    exhaustionConcern: false,
    mockPattern: "押し目待ちに適した銘柄"
  })
};

const fallbackStocks = ["7203", "6758", "8035", "9984", "TEST01", "TEST02", "TEST03", "TEST04", "TEST05"];

export function getMockStockData(query = "7203") {
  const normalized = String(query).trim().toLowerCase();
  const direct = mockStocks[normalized.toUpperCase()] || mockStocks[normalized];
  if (direct) return structuredClone(direct);

  const found = Object.values(mockStocks).find((stock) => {
    return stock.name.toLowerCase().includes(normalized)
      || stock.aliases.some((alias) => alias.toLowerCase().includes(normalized));
  });
  if (found) return structuredClone(found);

  const index = [...normalized].reduce((sum, char) => sum + char.charCodeAt(0), 0) % fallbackStocks.length;
  const stock = structuredClone(mockStocks[fallbackStocks[index]]);
  stock.code = normalized.match(/[a-z]*\d{2,4}/i)?.[0]?.toUpperCase() || "MOCK";
  stock.name = query ? `${query} 簡易モック銘柄 MOCK` : stock.name;
  return stock;
}

function createMockStock(stock) {
  const change = stock.price - stock.previousClose;
  const changePercent = stock.previousClose > 0 ? (change / stock.previousClose) * 100 : 0;
  return {
    ...mockMeta,
    ...stock,
    change,
    changePercent,
    averageVolume20d: stock.averageVolume20d,
    highYtd: stock.highYtd,
    largeUpperWickAfterVolumeSpike: stock.candlePattern === "VOLUME_SPIKE_UPPER_WICK"
  };
}
